theme: jekyll-theme-cayman
color: '#434343'
latest_version_number: 2
plugins:
  - jemoji
include:
  - _images
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
modes:
  - internal
algolia:
  application_id: Z1MM044EZ8
  index_name: theme
  search_only_api_key: cad8ec927860485f3a8ac1ce2372be28
